# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Kieran Lynch
tagline:          
description:      '2nd year computer science student at Aberystwyth University.'
url:              http://www.kieranjlynch.co.uk
baseurl:          /

author:
  name:           'Kieran Lynch'
  url:            https://www.kieranjlynch.co.uk

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/kil7
