# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Kieran Lynch
tagline:          
description:      '2nd year computer science student at Aberystwyth University.'
url:              http://kil7@github.io
baseurl:          /

author:
  name:           'Kieran Lynch'
  url:            https://kil7@github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
